site_name: 'CoderDojo TC Scratch'
nav:
  - Shared Mentor Resources: https://coderdojotc.github.io/CoderDojoTC/
  - Intro:
    - Getting Started: intro/01-getting-started.md
    - Summary of Labs: labs.md
    - Adding the Pen Extension: intro/02-list-of-blocks-used-in-intro.md
    - Drawing A Square: intro/03-first-square.md
    - Variables: intro/04-variables-square.md
    - Loops: intro/05-loops.md
    - Functions: intro/06-functions.md
    - Functions With Parameters: intro/07-functions-with-parameters.md
  - Presentations: presentations.md
  - Contact: contact.md

site_description: 'Resources for teaching Scratch to CoderDojo Twin Cities students.'
site_author: 'Dan McCreary'
repo_name: 'Scratch'
repo_url: 'https://github.com/CoderDojoTC/scratch'
edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/coderdojo-logo.png
  favicon: img/favicon.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  feature:
    tabs: true
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
plugins:
    - search
markdown_extensions:
  - codehilite
extra_css: 
  - stylesheets/extra.css