site_name: 'CoderDojo TC Scratch'
nav:
  - Intro:
    - Getting Started: menu-1/lesson-01.md
    - Sprite Movement: menu-1/lesson-02.md
  - Turtle:
    - Introduction: 01-intro.md
    - Adding CoderDojo Sprite: turtle/02-add-sprite.md
    - Adding Pen Extension: turtle/01-pen-extension.md
    - Drawing a Square: turtle/square.md
    - Variables: turtle/variable.md
    - Loops: turtle/loop.md
    - Conditionals: turtle/conditionals.md
    - Functions: turtle/functions.md
  - Advanced:
    - Lesson 1: menu-3/lesson-01.md
    - Lesson 2: menu-3/lesson-01.md
    
  - Contributing:
    - How to Contribute Examples: contribute.md
  - Contact:
    - Contact: contact.md

site_description: 'Resources for teaching Scratch to CoderDojo Twin Cities students.'
site_author: 'Dan McCreary'
repo_name: 'Scratch'
repo_url: 'https://github.com/CoderDojoTC/scratch'
edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/coderdojo-logo.png
  favicon: img/favicon.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  feature:
    tabs: true
  custom_dir: 'theme'
  include_sidebar: true
markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - codehilite:
      linenums: true
plugins:
    - search
markdown_extensions:
  - codehilite
extra_css: 
  - stylesheets/extra.css